### ISSUE TITLE
Add the auth0 test variables to the api workflow

### ISSUE THREAD

**Issue by gabrielbussolo** [calyptia/api#193]
# Bug Report

## Describe the bug

Intends to fix the tests that r blocking the pipeline as related on [calyptia/cloud#790](https://github.com/calyptia/cloud/issues/790)

## Which versions are affected

Please include component versions and any versioning information that is relevant
to reproduce.

## Reproducer steps

Logical enumerated sequence on how to reproduce the issue.

## Example code or configuration

```
Configuration or code that reproduces the issue
```

## Expected behavior

Please explain what should happen

## Current behavior

Please explain the current behavior

*Disclaimer: Please do not create a Pull Request without creating an issue first.*
Any change needs to be discussed before proceeding.
Failure to do so may result in the rejection of the pull request.

**Comment by builtbyproxy** [comment]
Thank you!

**Comment by patrick-stephens** [comment]
I'm going to re-open as we need a PR on calyptia/cloud as well.

**Comment by patrick-stephens** [comment]
Ah, we have https://github.com/calyptia/cloud/issues/790
