### ISSUE TITLE
Release typescript bindings separately 

### ISSUE THREAD

**Issue by gagoar** [calyptia/api#45]
# New feature request
Release typescript bindings separately 
## Describe the proposal
It will be healthy to push the bindings to npm so we can take advantage of dependebot or renovate for updates. 

Please enter a concise and clear description on what would you like to implement.
- Create a workflow that publishes an npm package under `@calyptia/api`

### Details of the technical implementation
we should just leverage what we already have in the readme. 
`npx openapi-typescript-codegen --input ./spec/open-api.yml --output ./ts-client --name Client` should be enough, and publish a package around that. 

### Checklist for proposal reviewer

- [ ] The proposal is clear on what changes need to be made in the code base.

- [ ] The proposal is clear on the architectural changes that will be affected.

- [ ] The proposal is clear on the breaking changes and how to mitigate them.

- [ ] The proposal is clear on what the deployment/configuration strategy is.

- [ ] The proposal is clean on how testing will validate the feature implementation.

### Reviewers

- [ ] Reviewed by a team member of the @calyptia/backend team
- [ ] Reviewed by a product owner.

### Disclaimers

- If there are multiple solutions, please present each one separately.
- Save comparisons for the very end.
- Please do not create a Pull Request without creating an issue first.
- Any change needs to be discussed before proceeding.
- Failure to do so may result in the rejection of the pull request.

**Comment by nicolasparada** [comment]
Just commenting here.
After adding pagination, the page info comes in the `Link` header.
The current generator we are using doesn't expose the headers in their API. Only the response body, or select **one** header to use as response body.

So we can either do two request one for the request body and another for the `Link` header.
Or switch generator.

Looking around, there is this one: https://github.com/anttiviljami/openapi-client-axios
It returns `data` which is the response body, and also the headers (it is axios).
Tho, it is not fully a generator. It works at runtime, but it can generate types for typescript so the runtime generated client can effectively use those types.

@gagoar @mlacosta 
Ultimately it is up to you guys.
From the API side, we can ditch the `Link` header and directly expose the cursor for pagination in the response body, but that would break the API. We would need to increase the version `/v2/`.

**Comment by gagoar** [comment]
I will like to try to make the current generator consider the link rather than switch to axios. 

I will use the API without the link /pagination (like we were using it before) and try to first add to the oss project the support. Happy and excited to do that actually. 

Would you mind (or @niedbalski ) make a note in the readme and create a ticket for me to take on this when we get the bandwidth? 


Thanks @nicolasparada for digging and coming up with options.

**Comment by nicolasparada** [comment]
The current generator allows to pass your own "request" file with the `--request` option flag.

Take a look at this custom example: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/b3530b14fc82ba285ff7940c750f50f37dd32bdb/test/custom/request.ts
This is the default request: https://github.com/ferdikoomen/openapi-typescript-codegen/blob/b3530b14fc82ba285ff7940c750f50f37dd32bdb/src/templates/core/fetch/request.hbs#L65-L94

**Comment by niedbalski** [comment]
> I will like to try to make the current generator consider the link rather than switch to axios.
> 
> I will use the API without the link /pagination (like we were using it before) and try to first add to the oss project the support. Happy and excited to do that actually.
> 
> Would you mind (or @niedbalski ) make a note in the readme and create a ticket for me to take on this when we get the bandwidth?
> 
> Thanks @nicolasparada for digging and coming up with options.

@gagoar https://github.com/calyptia/frontend/issues/176

**Comment by nicolasparada** [comment]
https://github.com/anymaniax/orval looks like a good alternative too.

**Comment by niedbalski** [comment]
I don't think we are handling this on this milestone, moved to next.
