### ISSUE TITLE
make sure optional relationships have omitempty json tag

### ISSUE THREAD

**Issue by nicolasparada** [calyptia/api#57]
See for example:
https://github.com/calyptia/api/blob/e1192968076a2bba68f63817d79d9e27e3aff65f/types/membership.go#L11

This is an optional relationship and right now it is returning `null` instead of omiting the field at all and is breaking the tests.

**Comment by niedbalski** [comment]
@nicolasparada are you planning to work on this fix?

**Comment by nicolasparada** [comment]
Right. Sure 👍

**Comment by niedbalski** [comment]
> Right. Sure 👍

Is there a PR linked to this issue @nicolasparada ?

**Comment by niedbalski** [comment]
Lets re-open if we plan to fix it.
